const binding = require('../binding')

module.exports = {
  windowFlags: {
    SDL_WINDOW_FULLSCREEN: binding.SDL_WINDOW_FULLSCREEN,
    SDL_WINDOW_OPENGL: binding.SDL_WINDOW_OPENGL,
    SDL_WINDOW_OCCLUDED: binding.SDL_WINDOW_OCCLUDED,
    SDL_WINDOW_HIDDEN: binding.SDL_WINDOW_HIDDEN,
    SDL_WINDOW_BORDERLESS: binding.SDL_WINDOW_BORDERLESS,
    SDL_WINDOW_RESIZABLE: binding.SDL_WINDOW_RESIZABLE,
    SDL_WINDOW_MINIMIZED: binding.SDL_WINDOW_MINIMIZED,
    SDL_WINDOW_MAXIMIZED: binding.SDL_WINDOW_MAXIMIZED,
    SDL_WINDOW_MOUSE_GRABBED: binding.SDL_WINDOW_MOUSE_GRABBED,
    SDL_WINDOW_INPUT_FOCUS: binding.SDL_WINDOW_INPUT_FOCUS,
    SDL_WINDOW_MOUSE_FOCUS: binding.SDL_WINDOW_MOUSE_FOCUS,
    SDL_WINDOW_EXTERNAL: binding.SDL_WINDOW_EXTERNAL,
    SDL_WINDOW_MODAL: binding.SDL_WINDOW_MODAL,
    SDL_WINDOW_HIGH_PIXEL_DENSITY: binding.SDL_WINDOW_HIGH_PIXEL_DENSITY,
    SDL_WINDOW_MOUSE_CAPTURE: binding.SDL_WINDOW_MOUSE_CAPTURE,
    SDL_WINDOW_ALWAYS_ON_TOP: binding.SDL_WINDOW_ALWAYS_ON_TOP,
    SDL_WINDOW_UTILITY: binding.SDL_WINDOW_UTILITY,
    SDL_WINDOW_TOOLTIP: binding.SDL_WINDOW_TOOLTIP,
    SDL_WINDOW_POPUP_MENU: binding.SDL_WINDOW_POPUP_MENU,
    SDL_WINDOW_KEYBOARD_GRABBED: binding.SDL_WINDOW_KEYBOARD_GRABBED,
    SDL_WINDOW_VULKAN: binding.SDL_WINDOW_VULKAN,
    SDL_WINDOW_METAL: binding.SDL_WINDOW_METAL,
    SDL_WINDOW_TRANSPARENT: binding.SDL_WINDOW_TRANSPARENT,
    SDL_WINDOW_NOT_FOCUSABLE: binding.SDL_WINDOW_NOT_FOCUSABLE
  }
}
