name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x64
          - os: macos-latest
            platform: darwin
            arch: arm64
          - os: windows-2022
            platform: win32
            arch: x64
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.tags }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - uses: ./.github/actions/virtual-audio-device
        with:
          platform: ${{ matrix.platform }}
      - run: |
          sudo apt update
          sudo apt install -y \
            libpulse-dev \
            libwayland-dev \
            libx11-dev \
            libxcursor-dev \
            libxext-dev \
            libxfixes-dev \
            libxi-dev \
            libxrandr-dev \
            pulseaudio \
            xvfb
        if: ${{ matrix.platform == 'linux' }}
      - run: choco install vb-cable -y
        if: ${{ matrix.platform == 'win32' }}
      - run: npm install -g bare-runtime bare-make
      - run: npm install
      - run: bare-make generate --platform ${{ matrix.platform }} --arch ${{ matrix.arch }} --debug ${{ matrix.flags }}
      - run: bare-make build
      - run: bare-make install
      - run: xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" npm test
        if: ${{ matrix.platform == 'linux' }}
      - run: npm test
        if: ${{ matrix.platform != 'linux' }}
